### ISSUE TITLE
several presets missing since last update (2.1.3)

### ISSUE THREAD

**Issue by boogaloo7** [oO-MrC-Oo/Milkdrop2-XBMC#2]
since the last Update (Kodi Milkdrop2 - 2.1.3) several presets are missing.

i.e.:
"martin - night cathedral"
"martin - moonlight splash"
"martin - butterflies"
"martin - liquid gold"
"martin - night in the forrest"
"martin - sunset over the river"

and so on.

it also ofthen crash now when switching presets

@AlwinEsch

**Comment by boogaloo7** [comment]
guess wrong place to report

**Comment by AlwinEsch** [comment]
Sorry on https://github.com/xbmc/visualization.milkdrop2 are no issues possible (and I have no rights to enable)

Have you a crash log about?

It just amazes me because of processing and the presets nothing has changed and the above are still inside.

I try also tommorow to make a check on Windows.
